<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Carter" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.Doctors.Application\Modules.Doctors.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Shared\Common.Shared.csproj" />
  </ItemGroup>

</Project>
