apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-config
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "Default": "Server=sqlserver;User Id=sa;Password=fiap12345$;Database=HealthAndMed;TrustServerCertificate=True;"
      },
      "MessageBroker": {
        "Host": "rabbitmq://mq/",
        "Username": "guest",
        "Password": "guest",
        "NumberOfRetries": 3,
        "KillSwitch": {
          "ActivationThreshold": 10,
          "TripThreshold": 0.15,
          "RestartMinutesTimeout": 1
        }
      },
      "Smtp": {
        "Sender": {
          "Name": "No reply",
          "Mail": "mock.no-reply@healthandmed.com"
        },
        "Host": "mailhog",
        "Port": 1025,
        "IsSecure": false
      },
        "Jwt": {
        "Secret": "healthandmedhackthonfiap2025apihealthandmed",
        "ExpirationInMinutes": 300,
        "Issuer": "healthandmedhackthonfiap2025apihealthandmed",
        "Audience": "healthandmedhackthonfiap2025apihealthandmed"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      }
    }
