apiVersion: v1
kind: Service
metadata:
  name: mq
spec:
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 30001
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: 30011
  selector:
    app: mq