<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.Patients.Persistence\Modules.Patients.Persistence.csproj" />
    <ProjectReference Include="..\Modules.Patients.Endpoints\Modules.Patients.Endpoints.csproj" />
    <ProjectReference Include="..\Modules.Patients.Application\Modules.Patients.Application.csproj" />
  </ItemGroup>

</Project>
