<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\..\Modules\Doctors\Modules.Doctors.CrossCutting.DependencyInjection\Modules.Doctors.CrossCutting.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\Modules\Patients\Modules.Patients.CrossCutting.DependencyInjection\Modules.Patients.CrossCutting.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
