<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Shared\Common.Shared.csproj" />
		<ProjectReference Include="..\Modules.Patients.Domain\Modules.Patients.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Modules.Patients.UnitTests" />
	</ItemGroup>

</Project>
